import React, { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { History, Printer } from "lucide-react";
import { cashierService } from "../../services/cashierService";
import { printCashierTicket } from "./cashierTicket";

const money = (value) => `${Number(value || 0).toLocaleString("vi-VN")} đ`;
export default function CashierHistoryPage() {
  const [message, setMessage] = useState("");
  const history = useQuery({ queryKey: ["cashier", "my-bookings"], queryFn: cashierService.getMyBookings });
  const print = async (id) => { try { setMessage(""); await printCashierTicket(await cashierService.getTicket(id)); } catch (error) { setMessage(error.response?.data?.message || error.message || "Không thể in vé."); } };
  return <div className="p-6 lg:p-8"><div className="mb-6 flex items-center gap-3"><History className="text-cyan-400"/><div><h1 className="text-3xl font-extrabold text-white">Lịch sử bán vé của tôi</h1><p className="text-slate-400">Chỉ hiển thị booking được tạo bằng tài khoản thu ngân này.</p></div></div>{message&&<p className="mb-4 rounded-xl bg-red-500/10 p-4 text-red-300">{message}</p>}{history.isPending?<p className="p-8 text-center text-slate-400">Đang tải...</p>:history.isError?<p className="p-8 text-center text-red-400">Không tải được lịch sử.</p>:<div className="overflow-x-auto rounded-2xl border border-white/10"><table className="w-full min-w-[820px] text-left text-sm"><thead className="bg-slate-800 text-slate-400"><tr><th className="p-4">Thời gian bán</th><th className="p-4">Phim / Suất</th><th className="p-4">Ghế</th><th className="p-4">Thanh toán</th><th className="p-4">Tổng tiền</th><th className="p-4"></th></tr></thead><tbody className="divide-y divide-white/5 bg-slate-900/50">{(history.data||[]).map(item=><tr key={item.id}><td className="p-4 text-slate-400">{item.created_at?new Date(item.created_at).toLocaleString("vi-VN"):"—"}</td><td className="p-4"><strong className="text-white">{item.show?.movie?.title||"—"}</strong><div className="text-slate-400">{item.show?.start_time?new Date(item.show.start_time).toLocaleString("vi-VN"):"—"}</div></td><td className="p-4 text-white">{item.bookingSeats.map(bs=>bs.seat?`${bs.seat.row}${bs.seat.number}`:"").filter(Boolean).join(", ")||"—"}</td><td className="p-4"><span className={item.payment_status==="paid"?"text-emerald-400":"text-amber-400"}>{item.payment_method?.toUpperCase()} · {item.payment_status}</span></td><td className="p-4 font-bold text-cyan-400">{money(item.total_price)}</td><td className="p-4"><button disabled={item.status!=="confirmed"} onClick={()=>print(item.id)} className="flex items-center gap-2 rounded-lg border border-amber-400/30 px-3 py-2 text-amber-300 disabled:opacity-30"><Printer size={16}/> In vé</button></td></tr>)}{!history.data?.length&&<tr><td colSpan="6" className="p-10 text-center text-slate-500">Bạn chưa bán vé nào.</td></tr>}</tbody></table></div>}</div>;
}
